### ISSUE TITLE
Remove Buffer dependency

### ISSUE THREAD

**Issue by dy** [miguelmota/arraybuffer-to-buffer#3]
That browserifies into heavy bundle. Interesting, is there a way to convert to `Buffer` w/o `Buffer` dependency?

**Comment by miguelmota** [comment]
@dy hmm since the browser doesn't have a native `Buffer` type so I don't know you can convert it to a Buffer type without a 3rd party module. The `buffer` npm module compressed is about 23KB which isn't the worst thing in the world

**Comment by dy** [comment]
We could do conditional require like

```js
try {
var Buffer = global.Buffer || require('buf' + 'fer').Buffer
} catch (e) {
// no Buffer in environment, safely fail
}
```

Then the `Buffer` would be included only if the other packages use that.
But https://github.com/browserify/browserify/issues/1881

(I know this is total overkill)

**Comment by miguelmota** [comment]
@dy interesting. I think browserify includes the buffer module regardless because browserify is meant to compile for the browser

**Comment by casr** [comment]
I just saw this via the linked issue. If you want to prevent `buffer` being sucked in on the browser-side you can do this in the `package.json`:

```json
{
  "browser": {
    "buffer": false
  }
}
```
And then code that uses `Buffer` might need to sniff the methods before use. E.g.
```js
if (typeof Buffer === 'function') {
  // Buffer available
}
```

**Comment by dy** [comment]
@casr just tried that - it does not work this way.
```json
 "buffer" : false
```
just blocks `Buffer` for that package even if the external packages require that. Related with https://github.com/browserify/browserify/issues/1881 I guess.

**Comment by casr** [comment]
Ah, okay. So, if I understand you correctly, you want `arraybuffer-to-buffer` to have a code path for if the `Buffer` object is available. And that that `Buffer` object is provided by some parent code that requires `arraybuffer-to-buffer`.

Is that correct?

**Comment by dy** [comment]
@casr yes. I want `arraybuffer-to-buffer` to include `buffer` only when the parent/sibling packages include that, and avoid otherwise.

Same situation is for the [typedarray-pool](https://github.com/mikolalysenko/typedarray-pool/issues/3), btw. People just opt out from using buffer at all, just because it bloats that small package.

There are also people forcing bundling buffer in small packages.

**Comment by casr** [comment]
There is still one thing I don't understand is why this should `arraybuffer-to-buffer` need to decide this? Surely the person bundling for the browser can either opt-out of `Buffer` by either providing a simple shim or just putting false on that key like before.

**Comment by dy** [comment]
We can delve into a lot of use scenarios, but generally speaking a package ideally should not cause unnecessary bloat of dependent packages - especially considering that likely arraybuffer-to-buffer is second/third-level dependency. Besides, not always that is possible to disable buffer globally - that can just break code, in particular this one. So basically we force consumer to write shim just in order to workaround things that are expected to work. Not a big deal of course.
